"""create_chat_tables

Revision ID: b459f462d10b
Revises: c51c74a40e02
Create Date: 2026-04-06 17:58:20.115656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b459f462d10b'
down_revision: Union[str, None] = 'c51c74a40e02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('buyer_id', sa.UUID(), nullable=False),
    sa.Column('seller_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_buyer_id'), 'conversations', ['buyer_id'], unique=False)
    op.create_index(op.f('ix_conversations_listing_id'), 'conversations', ['listing_id'], unique=False)
    op.create_index(op.f('ix_conversations_seller_id'), 'conversations', ['seller_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_listings_fts'), 'listings', [sa.literal_column("to_tsvector('russian'::regconfig, (((COALESCE(title, ''::character varying)::text || ' '::text) || COALESCE(address, ''::character varying)::text) || ' '::text) || COALESCE(description, ''::text))")], unique=False, postgresql_using='gin')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_seller_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_listing_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_buyer_id'), table_name='conversations')
    op.drop_table('conversations')
    # ### end Alembic commands ###
